import { ImageResponse } from "next/og";

// Default share/OG card for ocur.ai/be-ai. Per-result cards are generated by
// the /be-ai/card route and wired in via generateMetadata in page.tsx.
export const alt = "Be the AI — Ocur's reverse Turing test";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

const VOID = "#05080A";
const PHOS = "#3DF5A0";

function Mark({ size = 56 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 40 40" fill="none">
      <circle
        cx="20"
        cy="20"
        r="14"
        stroke={PHOS}
        strokeWidth="2.5"
        strokeDasharray="64 24"
        transform="rotate(-34 20 20)"
      />
      <circle cx="20" cy="20" r="5" fill={PHOS} />
    </svg>
  );
}

export default function Image() {
  return new ImageResponse(
    (
      <div
        style={{
          height: "100%",
          width: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: VOID,
          backgroundImage:
            "radial-gradient(50% 60% at 12% 0%, rgba(61,245,160,0.20), transparent), radial-gradient(45% 55% at 90% 10%, rgba(91,124,255,0.22), transparent), radial-gradient(55% 60% at 85% 100%, rgba(139,92,246,0.20), transparent)",
          padding: "76px",
          color: "white",
          fontFamily: "sans-serif",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 18 }}>
          <Mark />
          <div
            style={{
              display: "flex",
              fontSize: 26,
              letterSpacing: 6,
              color: "rgba(255,255,255,0.55)",
            }}
          >
            OCUR · REVERSE TURING TEST
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", alignItems: "flex-end", fontSize: 132, fontWeight: 700 }}>
            <span>Be the</span>
            <span style={{ color: PHOS, marginLeft: 28 }}>AI</span>
            <span>.</span>
          </div>
          <div
            style={{
              display: "flex",
              marginTop: 28,
              fontSize: 38,
              lineHeight: 1.3,
              color: "rgba(255,255,255,0.62)",
              maxWidth: 920,
            }}
          >
            Can you tell Ocur from a human pretending to be it?
          </div>
        </div>

        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            fontSize: 26,
            color: "rgba(255,255,255,0.5)",
          }}
        >
          <div style={{ display: "flex" }}>Play at ocur.ai/be-ai</div>
          <div style={{ display: "flex", color: PHOS }}>Made with Ocur</div>
        </div>
      </div>
    ),
    { ...size }
  );
}
